### ISSUE TITLE
Do no handle invalid Certificated on https connections

### ISSUE THREAD

**Issue by rebrec** [D35m0nd142/LFISuite#2]
Might be interesting to add (maybe optionnaly ?) a verify=False so that we can scan webserver which has self signed certificates ?

**Comment by D35m0nd142** [comment]
I never thought about it but I guess it is possible to add this feature. Have you already tried to scan such webservers with LFISuite?

**Comment by kildonan5** [comment]
I'm guessing this is the reason why LFISuite displays the error "Problem reaching 'https://x.x.x.x..... Problem connecting to the website."

**Comment by D35m0nd142** [comment]
I have added verify=False into every request in order to allow to scan and attack self-signed websites. Thanks also for the last suggestion, I have added the default path file to "pathtotest.txt".
